volumes:
  db:

services:

  nginx:
    container_name: wnr-nginx
    image: nginx:alpine
    volumes:
      - ./site:/var/www/site
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
    working_dir: /var/www/site
    ports:
      - 8080:81

  back:
    container_name: wnr-back
    user: 1000:1000
    build:
      context: ./
      dockerfile: docker-php
    volumes:
      - ./site:/var/www/site
    working_dir: /var/www/site
    environment:
      cookieValidationKey: 7Ewio5CtEzyYOO8n


  db:
    container_name: wnr-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: yii2basic
      POSTGRES_PASSWORD: pass
    volumes:
      - db:/var/lib/postgresql/data

  front:
    container_name: wnr-front
    image: node:alpine
    tty: true
    volumes:
      - ./site:/var/www/site
    user: 1000:1000
    working_dir: /var/www/site/front
